### ISSUE TITLE
Crawldir doesn't work with unicode characters in the path name

### ISSUE THREAD

**Issue by sihil** [pudo/aleph#131] opened 2017-01-30 14:34 UTC
When running the crawldir task I ran in to some problems with files named with non-ASCII characters. In my setup (clean Ubuntu 16.04) I found I had to set LANG / LC_ALL (not sure which did the trick) to a UTF8 value (en_GB.UTF-8) in order for these to be parsed and processed correctly. Without it I ended up with the exception below. 

Not sure if this is a documentation issue or could be made a default but it tripped me up.

```
[2017-01-30 13:20:32,881] ERROR in crawler: 'ascii' codec can't encode character u'\xc8' in position 62: ordinal not in range(128)
Traceback (most recent call last):
  File "/aleph/aleph/crawlers/crawler.py", line 71, in execute
    self.crawl(**kwargs)
  File "/aleph/aleph/crawlers/directory.py", line 31, in crawl
    ingest_directory(collection.id, meta, directory)
  File "/aleph/aleph/ingest/__init__.py", line 88, in ingest_directory
    base_path=entry_base, move=move)
  File "/aleph/aleph/ingest/__init__.py", line 88, in ingest_directory
    base_path=entry_base, move=move)
  File "/aleph/aleph/ingest/__init__.py", line 88, in ingest_directory
    base_path=entry_base, move=move)
  File "/aleph/aleph/ingest/__init__.py", line 88, in ingest_directory
    base_path=entry_base, move=move)
  File "/aleph/aleph/ingest/__init__.py", line 88, in ingest_directory
    base_path=entry_base, move=move)
  File "/aleph/aleph/ingest/__init__.py", line 58, in ingest_directory
    if not os.path.exists(local_path):
  File "/usr/lib/python2.7/genericpath.py", line 18, in exists
    os.stat(path)
```

**Comment by stas** [comment] 2017-01-30 16:06
Looks like an issue related to python. I was able to reproduce it and will take a look. Thank you!

**Comment by sihil** [comment] 2017-01-30 18:04
I think python defaults to assuming filenames are ASCII unless there is a LANG set (by default this is not the case in a docker container).

**Comment by pudo** [comment] 2017-01-30 18:50
We've been fighting weird path name issues (especially on Linux) for a good while now. The ingestor is supposed to call encoding detection on incoming pathname byte strings, but when there is only a short name it can fail and default to UTF-8 for something that isn't. Not quite sure how to handle that, what would be your preferred solution, @sihil?

**Comment by pudo** [comment] 2017-02-02 08:25
I've pushed the locale changes to the docker registry and upped the base image version, worth another shot now!

**Comment by pudo** [comment] 2017-02-11 10:00
Ok, I'm closing this as it's most likely the locale issue discussed above. If the issue still occurs, please let us know, @sihil. Thanks for reporting this.

**Closed by pudo** 2017-02-11 10:00 UTC
