### ISSUE TITLE
No ingestors found (fresh docker install)

### ISSUE THREAD

**Issue by cdharris** [pudo/aleph#126] opened 2017-01-06 10:59 UTC
Hi @pudo ! This software looks awesome and I've been trying to test it out, I've hit a problem after running a fresh `docker-compose up`. Would be very grateful for your time if you could point me in the right direction.

The app and services are started and I've edited the `aleph.env` with appropriate config and run the migrations as instructed. 

When I login and try and upload a pdf document to a collection, I receive the error
```
Traceback (most recent call last):
  File "/aleph/aleph/ingest/ingestor.py", line 109, in dispatch
    best_cls = cls.auction_file(meta, local_path)
  File "/aleph/aleph/ingest/ingestor.py", line 102, in auction_file
    meta.mime_type))
IngestorException: No ingestor found: u'test-document.pdf' (pdf, application/pdf)
```

it seems that `get_ingestors()` is returning empty `[]` even though I can see in `setup.py` the ingestors specified where they seem like they should be:
```
 entry_points={
        'aleph.ingestors': [
            'skip = aleph.ingest.dummy:SkipIngestor',
            'pdf = aleph.ingest.text:PDFIngestor',
            'doc = aleph.ingest.document:DocumentIngestor',
            ...
```

Q1. do you think this could be something to do with the application enviroment paths / the app not finding this list in the `setup.py` ?

Q2. Any advice on how to debug this app when running in Docker? I've tried editing the source on my host but it doesn't seem to be picked up by the app/worker running in the docker container, not sure if this is due to the mounted Docker volume or the setup of the image, or the python app running in memory, could you share any workflow tips here? 

Thanks a load,
Chris

**Comment by stas** [comment] 2017-01-06 13:10
Hey @cdharris,
thanks for the detailed report.
Could you confirm you did a fresh build of the docker images before you start the containers?
We recently did some changes to the way the installation is done, a full guide is available here:
http://aleph.readthedocs.io/en/latest/installation.html#development-installation-steps

In regards to the error you get, this happened to me before and it worked after removing any old containers and images and running a fresh build. In the meantime I could try to reproduce the error by running a fresh installation too if that helps.

**Comment by cdharris** [comment] 2017-01-07 13:32
Hi @stas I can confirm this issue was following a fresh build.

To make sure, I've just done a completely fresh build again (clean VM, clean docker installation, fresh git clone and following your build instructions)

To get the app and UI working there's two 'fixes' I had to include on both run throughs of the fresh install.

1. npm dependencies not available
```
aleph-docker-01 aleph # docker logs aleph_app_1
touch aleph/static/style/_custom.scss;
(test -f '' && cp -f  aleph/static/style/_custom.scss) || exit 0
./node_modules/webpack/bin/webpack.js --env.prod
make: ./node_modules/webpack/bin/webpack.js: Command not found
Makefile:14: recipe for target 'assets' failed
make: *** [assets] Error 127
```

I had to include an `npm install` in the `Makefile` for the app target to get this to work as webpack and other node modules were not there. 

Though it probably doesn't need to be run all the time and there's likely to be a better place for this.

2. Python package `dataparser` data files not available.
```
pp_1            | python aleph/manage.py runserver -h 0.0.0.0 -p 8000
app_1            | Traceback (most recent call last):
app_1            |   File "aleph/manage.py", line 8, in <module>
app_1            |     from aleph.core import create_app, archive, datasets
app_1            |   File "/aleph/aleph/__init__.py", line 5, in <module>
app_1            |     import urllib3
app_1            |   File "/usr/lib/python2.7/dist-packages/urllib3/__init__.py", line 10, in <module>
app_1            |     from .connectionpool import (
app_1            |   File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 10, in <module>
app_1            |     from queue import LifoQueue, Empty, Full
app_1            |   File "/aleph/aleph/queue.py", line 3, in <module>
app_1            |     from aleph.ingest import ingest_url, ingest  # noqa
app_1            |   File "/aleph/aleph/ingest/__init__.py", line 9, in <module>
app_1            |     from aleph.metadata import Metadata
app_1            |   File "/aleph/aleph/metadata/__init__.py", line 12, in <module>
app_1            |     from aleph.data.parse import parse_email, parse_country, parse_url
app_1            |   File "/aleph/aleph/data/parse.py", line 3, in <module>
app_1            |     import dateparser
app_1            |   File "/usr/local/lib/python2.7/dist-packages/dateparser/__init__.py", line 4, in <module>
app_1            |     from .date import DateDataParser
app_1            |   File "/usr/local/lib/python2.7/dist-packages/dateparser/date.py", line 11, in <module>
app_1            |     from dateparser.date_parser import date_parser
app_1            |   File "/usr/local/lib/python2.7/dist-packages/dateparser/date_parser.py", line 10, in <module>
app_1            |     from .conf import apply_settings
app_1            |   File "/usr/local/lib/python2.7/dist-packages/dateparser/conf.py", line 63, in <module>
app_1            |     settings = Settings()
app_1            |   File "/usr/local/lib/python2.7/dist-packages/dateparser/conf.py", line 33, in __init__
app_1            |     self._updateall(self._get_settings_from_yaml().items())
app_1            |   File "/usr/local/lib/python2.7/dist-packages/dateparser/conf.py", line 46, in _get_settings_from_yaml
app_1            |     data = get_data('data', 'settings.yaml')
app_1            |   File "/usr/lib/python2.7/pkgutil.py", line 591, in get_data
app_1            |     return loader.get_data(resource_name)
app_1            |   File "/usr/lib/python2.7/pkgutil.py", line 255, in get_data
app_1            |     return open(pathname, "rb").read()
app_1            | IOError: [Errno 2] No such file or directory: '/aleph/aleph/data/settings.yaml'
app_1            | Makefile:2: recipe for target 'web' failed
app_1            | make: *** [web] Error 1
```

To get this to work I had to copy all of files here https://github.com/scrapinghub/dateparser/tree/master/data into the '/aleph/aleph/data' folder.

I'm not sure what the proper fix might be but it seems to point to the package not being installed properly or something wrong with the Python environment? the dateparser`data/settings.yaml` and other files are available on the docker container in `/usr/local/lib/python2.7/dist-packages/data/`.


But even after these two 'fixes' I still end up with the same 'No ingestors found' error above. It seems like something might be missing from the install instructions or docker setup.

**Comment by stas** [comment] 2017-01-09 13:37
> npm dependencies not available

This is very weird. Could you paste the logs from the build. The Dockerfile we provide already includes `npm install` command.
https://github.com/pudo/aleph/blob/master/Dockerfile#L14

> Python package dateparser data files not available.

This is something we already discussed a bit with @pudo 
It looks like the proper module resolution fails since both aleph and dateparser provide a `data` (sub)-module.
We could either move the `manage.py` file outside the `aleph` package, or give up on `dateparser`.
A fix will definitely land in master very soon.

Trying to reproduce the issue I'm rebuilding the `pudo/aleph` image using `make build` and I was not able to replicate the issue with NPM.

Sorry for all the trouble with this. I will also update the docs to include steps on how to rebuild the image.

**Comment by pudo** [comment] 2017-01-11 17:53
I think using ``dateutil.parser`` would be a viable alternative to ``dateparser``, the main difference is that ``dateparser`` can parse more natural language style dates (i.e. lang-dep stuff like "15. März 2017"). This would allow us to get rid of this murky dep. WDYT, @stas? 

https://dateutil.readthedocs.io/en/stable/parser.html

**Comment by stas** [comment] 2017-01-11 21:08
Sounds good. I'll prepare a patch with some tests for tomorrow. Ty ty.

**Comment by pudo** [comment] 2017-01-19 09:32
Is this still occuring?

**Comment by pudo** [comment] 2017-02-02 08:15
Closing unless it's reported to still be an issue.

**Closed by pudo** 2017-02-02 08:15 UTC
Labels: bug

**Comment by olethanh** [comment] 2017-02-02 11:10
I confirm I also had to add the 'npm install' to the Make file in order for it to work.

I am new to Docker but may be it's because I don't have npm on the host system or the command is used before npm is installed?

I'm using Ubuntu Xenial with theses version:

- docker-compose version 1.10.0, build 4bd6f1a
- docker-py version: 2.0.1
- CPython version: 2.7.9
- OpenSSL version: OpenSSL 1.0.1t  3 May 2016
- Docker version 1.13.0, build 49bf474

**Comment by stas** [comment] 2017-02-02 13:26
@olethanh I'll try to take care of it in #130
